# Site settings
title: Knowledge Systems Group, cBio Center at DFCI
email: cerami@jimmy.harvard.edu
description: >
    The Knowledge Systems Group is an applied genomics software and data sciences group, focused on enabling cancer genomics
    research and precision cancer medicine at Dana-Farber Cancer Institute. 
baseurl: "/knowledge-systems"
url: "http://bcb.dfci.harvard.edu/knowledge-systems/"
fixedNav: 'true' # true or false
#theme: purple # green, blue, orange, purple, grey
twitterUsername:
githubUsername:
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: rdiscount
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
